{
  imports = [
    #./deluge.nix
    ./discord.nix
    #./dragon.nix
    ./firefox.nix
    ./font.nix
    ./gtk.nix
    #./kdeconnect.nix
    ./pavucontrol.nix
    #./playerctl.nix
    ./qt.nix
    #./slack.nix
    ./wayland-wm
    ./appimage.nix
    ./steam-run.nix
    ./sioyek.nix
    ./vscode.nix
    ./mullvad-vpn.nix
    ./anki.nix
  ];
}
