# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/profiles/qemu-guest.nix")
    #../common/optional/ephemeral-btrfs.nix
    ../common/optional/encrypted-root.nix
    ];
    
  boot = {
    initrd = {
      availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    };
    kernelModules = [ "kvm-amd" ];
    loader = {
      systemd-boot = {
        enable = true;
        consoleMode = "max";
      };
      efi.canTouchEfiVariables = true;
    };
  };

  fileSystems = {
    "/" = { 
      device = "/dev/disk/by-uuid/c45ddb47-4749-4133-91b9-6b8b336e75b8";
      fsType = "ext4";
     };
  };

  fileSystems = {
     "/boot" = { 
       device = "/dev/disk/by-uuid/EE5B-1F63";
       fsType = "vfat";
    };
  };
  
  swapDevices = [{ 
    device = "/dev/disk/by-uuid/2f1af931-ff2e-4ae9-b2cb-487dde7f76cd"; 
    }];
 
  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = true;
  # powerManagement.cpuFreqGovernor = "powersave";
}
